{ pkgs ? import <nixpkgs> { }
, lib ? pkgs.lib
, version ? "1.2.1"
, githubRepo ? "aztec-packages"
}:

let
  # Map Nix system to Barretenberg's platform naming
  # Note: Barretenberg uses different naming conventions based on version
  # v1.2.1 uses the newer convention: amd64/arm64 + darwin/linux
  platformInfo = {
    "x86_64-linux" = {
      arch = "amd64";
      platform = "linux";
    };
    "aarch64-linux" = {
      arch = "arm64";
      platform = "linux";
    };
    "x86_64-darwin" = {
      arch = "amd64";
      platform = "darwin";
    };
    "aarch64-darwin" = {
      arch = "arm64";
      platform = "darwin";
    };
  };

  # Import hashes from external file (generated by update-hashes.sh)
  hashes = (import ./hashes.nix).barretenberg;

  info = platformInfo.${pkgs.stdenv.hostPlatform.system} or (throw "Unsupported platform: ${pkgs.stdenv.hostPlatform.system}");

  # Construct the download URL
  url = "https://github.com/AztecProtocol/${githubRepo}/releases/download/v${version}/barretenberg-${info.arch}-${info.platform}.tar.gz";

  # Get hash for this version/platform, or use fakeHash for new versions
  hash = hashes.${version}.${pkgs.stdenv.hostPlatform.system} or lib.fakeHash;

in
pkgs.stdenv.mkDerivation {
  pname = "barretenberg";
  inherit version;

  src = pkgs.fetchurl {
    inherit url hash;
  };

  nativeBuildInputs = [ pkgs.makeWrapper ];

  sourceRoot = ".";

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin

    # Copy the bb binary
    cp bb $out/bin/bb
    chmod +x $out/bin/bb

    runHook postInstall
  '';

  meta = with lib; {
    description = "Barretenberg ZKP proving system - ${version}";
    homepage = "https://github.com/AztecProtocol/aztec-packages/tree/master/barretenberg";
    license = licenses.mit;
    platforms = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
    mainProgram = "bb";
  };
}
