# Generated by update-hashes.sh
# Do not edit manually - run ./update-hashes.sh to update
{
  noir = {
    "1.0.0-beta.13" = {
      "x86_64-linux" = "sha256-uwXlSFw6QULOkMrlD5V3xZ1LZXhShE5JGXkTRpY4/kg=";
      "aarch64-linux" = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
      "x86_64-darwin" = "sha256-DDj2RdWBWfhJJZlhtVnq+9/i8li2khogcQIQ9SbzY9U=";
      "aarch64-darwin" = "sha256-UBu/4k13y4LqzSNMxdsyLNJKqPD1l/sFXG9t98IdSmQ=";
    };
    "1.0.0-beta.14" = {
      "x86_64-linux" = "sha256-eFSjQLXOOfRxA2AxqpQIenzDKNICnR45du6t4v5Km7E=";
      "aarch64-linux" = "sha256-hjs820/grAXXgxbdxMxuKaqqaeFF7ASwiSgibfi7ifw=";
      "x86_64-darwin" = "sha256-b8vBYEvwEaYNA/5VbQRVRm32Sh4bH0Ck6KojvBQpJyo=";
      "aarch64-darwin" = "sha256-K7hWqG6eB66U4FJpnr05FCZTTTD+Q3g71oc/Yoo6aZs=";
    };
    "1.0.0-beta.15" = {
      "x86_64-linux" = "sha256-yhxkN1COGVKU5jDlhmsXuVbg1asMmWJbN5ulQAHVnDk=";
      "aarch64-linux" = "sha256-X8XkOeBfr2TOAmcsd52zf3EKO4kLOmXiaj0SSzxbpoc=";
      "x86_64-darwin" = "sha256-uDDq9GQWMny2Ee+xEWLdo9mXSAC9xKM1HBsnI3t2Y1I=";
      "aarch64-darwin" = "sha256-gEFMsn6rN/0/T7Iaw8A7Crq6XrR5PWQ9sLxC6yyJdIg=";
    };
    "1.0.0-beta.16" = {
      "x86_64-linux" = "sha256-JGtP6KaUwIXThMdDGTAWAOLsWnwzfVEAY5g5PQI+rxE=";
      "aarch64-linux" = "sha256-DfU2EbvjzQ0csEwxwjKAsx7FtlzY/tnPSjVRTnwn8q0=";
      "x86_64-darwin" = "sha256-ReNgZsGT3eJYNa1WnD0t3lJ3nvdCcxotD+zOyaU/SO0=";
      "aarch64-darwin" = "sha256-4h1tCWOYMVaIULNlAC4MYEVjKBVbFDKWzPb7PKTOx5Q=";
    };
    "1.0.0-beta.17" = {
      "x86_64-linux" = "sha256-VyaTNBahWZW/WGgi5DJrmUgr8C4k+sa/5muOU4cfMxU=";
      "aarch64-linux" = "sha256-ecpBmJLU7vgBddItyn0sTgjAEKDJjzXEdGv1zhXtF/4=";
      "x86_64-darwin" = "sha256-oc3j/HUA+0C0HJLla9HRIuvIXmy8bgxJoWQgVxpIGlA=";
      "aarch64-darwin" = "sha256-kqhwO7T1tE9Sr7P5Gkh+FVjrwAGxAUQazDIFSAS3srk=";
    };
    "1.0.0-beta.18" = {
      "x86_64-linux" = "sha256-t8Oaa/329YdoXHDONZMFqbGdZE55u9GWkvTVYETWTyw=";
      "aarch64-linux" = "sha256-hipD+Hs3GhY5YLCrX9kgoUUC0q8zdGB6m1Ll3WZFBoc=";
      "x86_64-darwin" = "sha256-EVbEHJtfecHt57prCbhKFS5N5dtCpNgHu+p/QeRaAvg=";
      "aarch64-darwin" = "sha256-7WfZ80kKOR+a4rRUp/ZDPfWr/jfgu9sOTiggjaHvnUE=";
    };
    "1.0.0-beta.19" = {
      "x86_64-linux" = "sha256-t3ScdOdW2OjQLeXX5NmkQbTBhlZ0tI9ug7YhT7O4C+U=";
      "aarch64-linux" = "sha256-3br3C+KpU3AZYq/vjOGFF7f3fXdoXQcPCBIXM5Zqe/s=";
      "x86_64-darwin" = "sha256-QVQni4ZXhrvzxQZJRKe4RQ9J2mmtIqPJcYJvazNmaOs=";
      "aarch64-darwin" = "sha256-PQIUPvzAalyZH2m7a7dw5jkjBUnWTzXtE977REILenU=";
    };
    "1.0.0-beta.20" = {
      "x86_64-linux" = "sha256-qe9NvsEYxpGtSpbtv6j5zVSz95VCc/VN4RVya2lthGk=";
      "aarch64-linux" = "sha256-aSbYqhCArqs+xTjqNkR+3e1dLsoBGKttVIxeDuiow7M=";
      "x86_64-darwin" = "sha256-GA3ff6yOvFd9GGbtUQH7PrUaXep7sTUcu8M4V8jbtEc=";
      "aarch64-darwin" = "sha256-EPWFgvZcbkwQNtxAvmEJr1gc7X8Gt4RevhYXwdwB0wQ=";
    };
    "1.0.0-beta.21" = {
      "x86_64-linux" = "sha256-7XsG+1JyjqaWQ3lAXPR8TfyyJlmgVUEZZ8u0IdrU9fQ=";
      "aarch64-linux" = "sha256-rDw7wD6LbaEsSK69xuCXpm9YbCE6PTeB6Bk1+BEgr+c=";
      "x86_64-darwin" = "sha256-CSAhhDdcXemm6hc3gu6qm/ze1wVxXrZozw8xhFB8B/0=";
      "aarch64-darwin" = "sha256-eMucu0ydFz7wsiqer4CgD7QzgseIaK6CDjdUJP1vTnE=";
    };
    "1.0.0-beta.22" = {
      "x86_64-linux" = "sha256-OExPyACQWyE+Jqq9c4qWpKhbGnb/wn+xmuttM0lKeHs=";
      "aarch64-linux" = "sha256-nge0NhSLseidEqTSBD5hPqX9gffVUY6BBOJymLOcMUo=";
      "x86_64-darwin" = "sha256-c2G5KBP9vegPUC6N3QRApXsF6A1YpYBDg31GCNoSKB8=";
      "aarch64-darwin" = "sha256-RF2smSWPhnsBagU1Pqx798HP7ia5i2jMhRu1fsVpqRw=";
    };
    "1.0.0-beta.23" = {
      "x86_64-linux" = "sha256-bXwyhNNid31dViBAs/QrSo94HDX6jlk0PyG8EEFzsIQ=";
      "aarch64-linux" = "sha256-axPh1R8rnHf42/axZZ65r1sBpOukiGhPZGDA94qZO6Y=";
      "x86_64-darwin" = "sha256-sWnDYRWeOiBaTyWHIgQ7NLlwjxuUadA2Ec6p6gyiSBk=";
      "aarch64-darwin" = "sha256-kx3Ypf+tOJircbQl7EGzi0tGcwcH5BODa8PKBPab7II=";
    };
    "1.0.0-beta.24" = {
      "x86_64-linux" = "sha256-3uTUqKwm4CC/YKFrNKpn2VU6c0rpffZIN01mpgLx0yk=";
      "aarch64-linux" = "sha256-FQ7U40PpT90TAY0olOtBd+KQ41wT1YjnhLXtJKhGKFQ=";
      "x86_64-darwin" = "sha256-/visbPwcWtz6vanRRwwLP1LWISFcX/4NS3jDMoWqDt4=";
      "aarch64-darwin" = "sha256-TsWuoz0Rvs3HPIOoN7YfLdgCjM3znhB/1Gfjx07E3eo=";
    };
    "1.0.0-beta.25" = {
      "x86_64-linux" = "sha256-vzQQq5STOkrr0fmItnrpdMbCJ/lFbtDx5KNxa7ijD+k=";
      "aarch64-linux" = "sha256-ToZVOvmeh8BHuuQPExUjRwno2BX2FY87igC/aPUSorc=";
      "x86_64-darwin" = "sha256-ZgVnxkX4QTibHjfd69T2x1QXdjAY6gNOCLKDOL8nZzw=";
      "aarch64-darwin" = "sha256-Y+1FPQmmW/x47vYyUkIxJpWdQchd4NoM9UKJxeJmzrU=";
    };
    "1.0.0-beta.8" = {
      "x86_64-linux" = "sha256-MzbkLwBhOPObwbbnHs5u7q+cGL5BwLcNBLCMLXWBCGw=";
      "aarch64-linux" = "sha256-2NnPRF6WP3VCIVj+3W2B8+sGlB8gEiF26BDvZFmI8ME=";
      "x86_64-darwin" = "sha256-/2ZaDoMoJLb3sCWl7fXoZ3Qebb5rVrsDEaOCw+lQyns=";
      "aarch64-darwin" = "sha256-4IsSbgeCeUfiXDeWbHFAyyCWHDKD8Ceq3lql315b1Ao=";
    };
  };

  nargo-t256 = {
    "0c11d1b6d8cef3eeab8a276066d1ae8e4139fed6" = {
      srcHash = "sha256-9KchEimHhDeL16zNmakwmUGNKfcw4MdrStyXKuau1Zs=";
      cargoHash = "sha256-LNfYXtjkitpD/S2BqH4qKzwGjWyUJRzyRzTydKCy+38=";
    };
    "t256-v0.1" = {
      srcHash = "sha256-54L9F98ZjefI6DD2HkeP/ebsGEGISMs5WLNlI33y5/8=";
      cargoHash = "sha256-LNfYXtjkitpD/S2BqH4qKzwGjWyUJRzyRzTydKCy+38=";
    };
    "t256-v0.2" = {
      srcHash = "sha256-0BomTd5b9PF0QijXD3kKDrMUaj54PCdRJPSR1Z/2rck=";
      cargoHash = "sha256-6O1ILolDDJ+YfclFXm71a6tw38PKWJ/supw26H/sA90=";
    };
    "t256-v0.22" = {
      srcHash = "sha256-ybarJDT69udlAfJqJ3u12gwGC5Ieh48f8+8X68WvNls=";
      cargoHash = "sha256-sSOT2+pIJCT+0RiP7dGW4fd0HVaPR3foR5WEq0uWooE=";
    };
    "t256-v0.22-1" = {
      srcHash = "sha256-kduSlSyWiVseGIndthhMoJuHb35O84ot29i6ezcGwFQ=";
      cargoHash = "sha256-sSOT2+pIJCT+0RiP7dGW4fd0HVaPR3foR5WEq0uWooE=";
    };
    "t256-v0.23" = {
      srcHash = "sha256-Ynv2mNedTIkqrh1V4FBQBSGarJ2G3rjIdqCSSjkDdkY=";
      cargoHash = "sha256-DoF7fdznTjbS3UsHfUuiDBzm2GyrwINpD9btpp9n7kY=";
    };
    "t256-v0.24" = {
      srcHash = "sha256-UpoWu1k8lKWmlkaEPxkoNuNyIdh4nwq50bK930BiUHI=";
      cargoHash = "sha256-wfFn2sPrfbnAnlH08f5zN+n1VlRQYKt0FqY1zAzy0p4=";
    };
    "t256-v0.25" = {
      srcHash = "sha256-SN9f63Sz7Vkt7Vh08S6OVZX+LLh2Z+tXR+ualfd1fnk=";
      cargoHash = "sha256-PneK3doubuKFA5uGYx633JFmEN4KvA1zbcsRFe/OBF0=";
    };
  };

  barretenberg = {
    "0.87.0" = {
      "x86_64-linux" = "sha256-gptxQocIX/RWK6LGT5yBKEY2UNgzvdHbXVozRx3NZ8s=";
      "aarch64-linux" = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
      "x86_64-darwin" = "sha256-qZZTQDHImLZRIxl5eShKqSvTd8HrwTMYqCR2qC+cx4E=";
      "aarch64-darwin" = "sha256-KQB5GdS63qBH9mD1W8vDis1uiPB3Isxj+EuuyBa+F1E=";
    };
    "1.2.1" = {
      "x86_64-linux" = "sha256-wuwglyhb5xR2QZIru8HPFYV4jbPNF5D7yqPmxDokXqQ=";
      "aarch64-linux" = "sha256-bPV7YpuYTQNXYV2f2lRKzXEMKh/7Z9CJMRM6LW+OWGA=";
      "x86_64-darwin" = "sha256-5OunMg0WiqXnUMwDIePEAYQEuOatwIZmdKwSaVRu3K4=";
      "aarch64-darwin" = "sha256-ZbvwZDKZxEIQnspv3LiMrTlLZm6hii07quUHHp/V1qc=";
    };
    "2.1.2" = {
      "x86_64-linux" = "sha256-tNYAoSAsDibfwHwDN6fR0q53rpuC1SBZPKcQFO8x1KI=";
      "aarch64-linux" = "sha256-iD+L8a1UeIS/CMFmXSgW6uwjkW2bouCZ9rfkIz6pJsI=";
      "x86_64-darwin" = "sha256-lxFLyKyIv6uUj/BLeu/kiMlm+2nKIpK9/rlOGZPo6ao=";
      "aarch64-darwin" = "sha256-qco1FlURRLFy3Fmfr1vMVFz0mz5LDGUq7UtgTPtv2yw=";
    };
    "2.1.8" = {
      "x86_64-linux" = "sha256-8FpNEWO0iUsGqtm+8wvJrOPOroCH8TsYGxT/K+kJwNA=";
      "aarch64-linux" = "sha256-uXA9pBlFMPpdRHioLbURsCxvYy0z+xdKO5LNBpGv5v0=";
      "x86_64-darwin" = "sha256-5TFazO7rihU3MFELRGTTtNiphPhajN3k9wplwm29tSs=";
      "aarch64-darwin" = "sha256-4x2XvR60zVRfFMrg+vhiEeP601y+sWTqJdQcUzHyons=";
    };
    "3.0.0-nightly.20251030-2" = {
      "x86_64-linux" = "sha256-ptiHQGOIRsDvWe2GlDPnWRA677wIZmZdjgH7TD9UU7k=";
      "aarch64-linux" = "sha256-Atcu/yyE9N1WlDYp7kLMN9bKSXXNJ5inajnSqFRnJ/4=";
      "x86_64-darwin" = "sha256-jRBDanNJFF/XCpMHlgdC1CzYTKNOR6UYaSmjZhuKeZE=";
      "aarch64-darwin" = "sha256-e7olhXZysf5zulF2H+OQa8h9hNXEN7LjQ/P2OHVKopU=";
    };
    "3.0.0-nightly.20251104" = {
      "x86_64-linux" = "sha256-xtrhCS/tjRIwwjRf/PTJA6LXh9DiIOnqjJSwUR7SnJs=";
      "aarch64-linux" = "sha256-euLRC6Q1wqwvjNpWBOZugbsZoWfXNerxLV5Mfyrr7qU=";
      "x86_64-darwin" = "sha256-kr7idMSfHAP13j8RFKuL0/LZQADnZFmkbWA0B+vXfUU=";
      "aarch64-darwin" = "sha256-/DCSL47i24aj+w3coCb4q0zxI+bP+7/xcWnt5Q5RPvQ=";
    };
    "3.0.0-nightly.20260102" = {
      "x86_64-linux" = "sha256-CkozGkDvGk8OL7dFw4oC4svTKppecRiNbw2T6+5Sox8=";
      "aarch64-linux" = "sha256-Ym1LK3wIldnU8bbHSUFoXBRCD0xNII+hm+Zw9IZ4j7c=";
      "x86_64-darwin" = "sha256-d0DM12k278EugFksf1mlLiwEWkrvSrarkCE7c0ArUh8=";
      "aarch64-darwin" = "sha256-fJw/1Kmjv+BUHq+Zoc0Otg+zZjU6wQiy0Hu+c76w/LA=";
    };
    "4.0.0-nightly.20260120" = {
      "x86_64-linux" = "sha256-Ynh0LZ9qYmVh+bwy6VSlMlI4/tYrdayNLtEJ7m2cK6E=";
      "aarch64-linux" = "sha256-XsCDuNNJJMkT43rBTSqlv5i7voPKEC58K/KNv7YbcAo=";
      "x86_64-darwin" = "sha256-8yWiAbVO9ljkhIJo+9xIIcwk0PH2ElhHVTNcmRuTTKw=";
      "aarch64-darwin" = "sha256-beYTI4hCu9k0STLwJnqHBX4lrqir4S2Nf+X1UItWPrA=";
    };
    "5.0.0" = {
      "x86_64-linux" = "sha256-S0KmSgWH4eFQifeiDIf6LYoJKstPyVRlp5inO5i6eU0=";
      "aarch64-linux" = "sha256-o9HwpV7ICkv1zjuGYXASuNvJdLmGuxAGfBZ0ZaeaSMs=";
      "x86_64-darwin" = "sha256-MRV/u4EokXi1dgizs9+KvcKGXf3qcs3jr69SaedX+YY=";
      "aarch64-darwin" = "sha256-lVk4DwGGTFkBdhsnXDsH4Fk4l5IqLUFa0jvPnLR9+e4=";
    };
    "5.0.0-nightly.20260324" = {
      "x86_64-linux" = "sha256-eHWnqCwjKIRhva8JvfBTobC7sAZrHis7x/uMoHUY4XQ=";
      "aarch64-linux" = "sha256-91DwZa7qJ7XbIEVUljFxhhYPzNUJY1fFPTgmBocwHj0=";
      "x86_64-darwin" = "sha256-viH5nBgEmcB/7192Xv9jY54OavJ4qcxtPaxPJq9ajKs=";
      "aarch64-darwin" = "sha256-x1vc00QiQCASBOOaOe8zV5bZKp4NVTfgpfEoexHgHZ8=";
    };
    "5.0.0-nightly.20260522" = {
      "x86_64-linux" = "sha256-0gfskPv6L7ok16R7enWJLuBSt5hCUrhmpKDBtSluFXE=";
      "aarch64-linux" = "sha256-toQup1wXH9hLXo+gr3X2ESHQw97hxS4Xt/jXYZpBif4=";
      "x86_64-darwin" = "sha256-nKLidfeSVjXxJB6uTBh0keT7jaxfv2SctllvrGIdQ/w=";
      "aarch64-darwin" = "sha256-9WbEi6DaznCno0ZNrhFXxuabUmCx4uwPV5cT+eenAwA=";
    };
  };
}
