# Generated by update-hashes.sh
# Do not edit manually - run ./update-hashes.sh to update
{
  noir = {
    "1.0.0-beta.13" = {
      "x86_64-linux" = "sha256-uwXlSFw6QULOkMrlD5V3xZ1LZXhShE5JGXkTRpY4/kg=";
      "aarch64-linux" = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
      "x86_64-darwin" = "sha256-DDj2RdWBWfhJJZlhtVnq+9/i8li2khogcQIQ9SbzY9U=";
      "aarch64-darwin" = "sha256-UBu/4k13y4LqzSNMxdsyLNJKqPD1l/sFXG9t98IdSmQ=";
    };
    "1.0.0-beta.14" = {
      "x86_64-linux" = "sha256-eFSjQLXOOfRxA2AxqpQIenzDKNICnR45du6t4v5Km7E=";
      "aarch64-linux" = "sha256-hjs820/grAXXgxbdxMxuKaqqaeFF7ASwiSgibfi7ifw=";
      "x86_64-darwin" = "sha256-b8vBYEvwEaYNA/5VbQRVRm32Sh4bH0Ck6KojvBQpJyo=";
      "aarch64-darwin" = "sha256-K7hWqG6eB66U4FJpnr05FCZTTTD+Q3g71oc/Yoo6aZs=";
    };
    "1.0.0-beta.15" = {
      "x86_64-linux" = "sha256-yhxkN1COGVKU5jDlhmsXuVbg1asMmWJbN5ulQAHVnDk=";
      "aarch64-linux" = "sha256-X8XkOeBfr2TOAmcsd52zf3EKO4kLOmXiaj0SSzxbpoc=";
      "x86_64-darwin" = "sha256-uDDq9GQWMny2Ee+xEWLdo9mXSAC9xKM1HBsnI3t2Y1I=";
      "aarch64-darwin" = "sha256-gEFMsn6rN/0/T7Iaw8A7Crq6XrR5PWQ9sLxC6yyJdIg=";
    };
    "1.0.0-beta.16" = {
      "x86_64-linux" = "sha256-JGtP6KaUwIXThMdDGTAWAOLsWnwzfVEAY5g5PQI+rxE=";
      "aarch64-linux" = "sha256-DfU2EbvjzQ0csEwxwjKAsx7FtlzY/tnPSjVRTnwn8q0=";
      "x86_64-darwin" = "sha256-ReNgZsGT3eJYNa1WnD0t3lJ3nvdCcxotD+zOyaU/SO0=";
      "aarch64-darwin" = "sha256-4h1tCWOYMVaIULNlAC4MYEVjKBVbFDKWzPb7PKTOx5Q=";
    };
    "1.0.0-beta.17" = {
      "x86_64-linux" = "sha256-VyaTNBahWZW/WGgi5DJrmUgr8C4k+sa/5muOU4cfMxU=";
      "aarch64-linux" = "sha256-ecpBmJLU7vgBddItyn0sTgjAEKDJjzXEdGv1zhXtF/4=";
      "x86_64-darwin" = "sha256-oc3j/HUA+0C0HJLla9HRIuvIXmy8bgxJoWQgVxpIGlA=";
      "aarch64-darwin" = "sha256-kqhwO7T1tE9Sr7P5Gkh+FVjrwAGxAUQazDIFSAS3srk=";
    };
    "1.0.0-beta.18" = {
      "x86_64-linux" = "sha256-t8Oaa/329YdoXHDONZMFqbGdZE55u9GWkvTVYETWTyw=";
      "aarch64-linux" = "sha256-hipD+Hs3GhY5YLCrX9kgoUUC0q8zdGB6m1Ll3WZFBoc=";
      "x86_64-darwin" = "sha256-EVbEHJtfecHt57prCbhKFS5N5dtCpNgHu+p/QeRaAvg=";
      "aarch64-darwin" = "sha256-7WfZ80kKOR+a4rRUp/ZDPfWr/jfgu9sOTiggjaHvnUE=";
    };
    "1.0.0-beta.19" = {
      "x86_64-linux" = "sha256-t3ScdOdW2OjQLeXX5NmkQbTBhlZ0tI9ug7YhT7O4C+U=";
      "aarch64-linux" = "sha256-3br3C+KpU3AZYq/vjOGFF7f3fXdoXQcPCBIXM5Zqe/s=";
      "x86_64-darwin" = "sha256-QVQni4ZXhrvzxQZJRKe4RQ9J2mmtIqPJcYJvazNmaOs=";
      "aarch64-darwin" = "sha256-PQIUPvzAalyZH2m7a7dw5jkjBUnWTzXtE977REILenU=";
    };
    "1.0.0-beta.20" = {
      "x86_64-linux" = "sha256-qe9NvsEYxpGtSpbtv6j5zVSz95VCc/VN4RVya2lthGk=";
      "aarch64-linux" = "sha256-aSbYqhCArqs+xTjqNkR+3e1dLsoBGKttVIxeDuiow7M=";
      "x86_64-darwin" = "sha256-GA3ff6yOvFd9GGbtUQH7PrUaXep7sTUcu8M4V8jbtEc=";
      "aarch64-darwin" = "sha256-EPWFgvZcbkwQNtxAvmEJr1gc7X8Gt4RevhYXwdwB0wQ=";
    };
    "1.0.0-beta.21" = {
      "x86_64-linux" = "sha256-7XsG+1JyjqaWQ3lAXPR8TfyyJlmgVUEZZ8u0IdrU9fQ=";
      "aarch64-linux" = "sha256-rDw7wD6LbaEsSK69xuCXpm9YbCE6PTeB6Bk1+BEgr+c=";
      "x86_64-darwin" = "sha256-CSAhhDdcXemm6hc3gu6qm/ze1wVxXrZozw8xhFB8B/0=";
      "aarch64-darwin" = "sha256-eMucu0ydFz7wsiqer4CgD7QzgseIaK6CDjdUJP1vTnE=";
    };
    "1.0.0-beta.8" = {
      "x86_64-linux" = "sha256-MzbkLwBhOPObwbbnHs5u7q+cGL5BwLcNBLCMLXWBCGw=";
      "aarch64-linux" = "sha256-2NnPRF6WP3VCIVj+3W2B8+sGlB8gEiF26BDvZFmI8ME=";
      "x86_64-darwin" = "sha256-/2ZaDoMoJLb3sCWl7fXoZ3Qebb5rVrsDEaOCw+lQyns=";
      "aarch64-darwin" = "sha256-4IsSbgeCeUfiXDeWbHFAyyCWHDKD8Ceq3lql315b1Ao=";
    };
  };

  barretenberg = {
    "0.87.0" = {
      "x86_64-linux" = "sha256-gptxQocIX/RWK6LGT5yBKEY2UNgzvdHbXVozRx3NZ8s=";
      "aarch64-linux" = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
      "x86_64-darwin" = "sha256-qZZTQDHImLZRIxl5eShKqSvTd8HrwTMYqCR2qC+cx4E=";
      "aarch64-darwin" = "sha256-KQB5GdS63qBH9mD1W8vDis1uiPB3Isxj+EuuyBa+F1E=";
    };
    "1.2.1" = {
      "x86_64-linux" = "sha256-wuwglyhb5xR2QZIru8HPFYV4jbPNF5D7yqPmxDokXqQ=";
      "aarch64-linux" = "sha256-bPV7YpuYTQNXYV2f2lRKzXEMKh/7Z9CJMRM6LW+OWGA=";
      "x86_64-darwin" = "sha256-5OunMg0WiqXnUMwDIePEAYQEuOatwIZmdKwSaVRu3K4=";
      "aarch64-darwin" = "sha256-ZbvwZDKZxEIQnspv3LiMrTlLZm6hii07quUHHp/V1qc=";
    };
    "2.1.2" = {
      "x86_64-linux" = "sha256-tNYAoSAsDibfwHwDN6fR0q53rpuC1SBZPKcQFO8x1KI=";
      "aarch64-linux" = "sha256-iD+L8a1UeIS/CMFmXSgW6uwjkW2bouCZ9rfkIz6pJsI=";
      "x86_64-darwin" = "sha256-lxFLyKyIv6uUj/BLeu/kiMlm+2nKIpK9/rlOGZPo6ao=";
      "aarch64-darwin" = "sha256-qco1FlURRLFy3Fmfr1vMVFz0mz5LDGUq7UtgTPtv2yw=";
    };
    "2.1.8" = {
      "x86_64-linux" = "sha256-8FpNEWO0iUsGqtm+8wvJrOPOroCH8TsYGxT/K+kJwNA=";
      "aarch64-linux" = "sha256-uXA9pBlFMPpdRHioLbURsCxvYy0z+xdKO5LNBpGv5v0=";
      "x86_64-darwin" = "sha256-5TFazO7rihU3MFELRGTTtNiphPhajN3k9wplwm29tSs=";
      "aarch64-darwin" = "sha256-4x2XvR60zVRfFMrg+vhiEeP601y+sWTqJdQcUzHyons=";
    };
    "3.0.0-nightly.20251030-2" = {
      "x86_64-linux" = "sha256-NakQkT36MWmJ5a4oYce33waX1xwmhxKhprbr7nPRKew=";
      "aarch64-linux" = "sha256-EulriUMoG6cD2SwW3MiRTfhwUINajxOpY/DysFnDM5Y=";
      "x86_64-darwin" = "sha256-Piz6byJ/lX/9gNxVY7tvU3Tk1mvSQW428GQbcmX1018=";
      "aarch64-darwin" = "sha256-SveDhJ3CfkWDFK3Du8l1lg/1RoZPR2Q66edTU1TZFUw=";
    };
    "3.0.0-nightly.20251104" = {
      "x86_64-linux" = "sha256-l0ABPRqg6xsLstcUhMiz3rxQUKQJvV8S+EVPv8fLVBk=";
      "aarch64-linux" = "sha256-rmv4UYmYUjtOE1zWOPMFqAL1Lo36XqmxwhDefQTFU0M=";
      "x86_64-darwin" = "sha256-eHRJTdEjhlWZOkS4XZTp3MNYnSmYDv+LA6fxZ6RcMuQ=";
      "aarch64-darwin" = "sha256-bTU8BdvsxXPRsMqZLIsiLbjoc4U7eRC3kpFWKTR/Z4k=";
    };
    "3.0.0-nightly.20251105" = {
      "x86_64-linux" = "sha256-5yjd4/hMqQhNNzgknbuxm9uCIkzClQvU4cUxqzW29bo=";
      "aarch64-linux" = "sha256-sRGcybMAt9bgIr/8oahyJnw6bEjlCqqMAq9ecJ7bLXg=";
      "x86_64-darwin" = "sha256-FtZO78IoLvtKni12ajrU21krvwHu57wBjVjScS4WvVU=";
      "aarch64-darwin" = "sha256-kQHV0aqo3ePSma1Vy2vcIMCZWciJxirajahpnRadkWg=";
    };
    "3.0.0-nightly.20260102" = {
      "x86_64-linux" = "sha256-SEeugqHSX5SJBX2iwz0ave47pFfoIZAoosIzb4UPjNc=";
      "aarch64-linux" = "sha256-pnUiGoI/b62m0BsJocJsD3NWVn8xqRKiR1tuO2PUOKI=";
      "x86_64-darwin" = "sha256-kTe0m+Vr/qW2IgO3rky2fJ7MEv4WkqibrfLPS1cyP9w=";
      "aarch64-darwin" = "sha256-fJw/1Kmjv+BUHq+Zoc0Otg+zZjU6wQiy0Hu+c76w/LA=";
    };
    "4.0.0-nightly.20260120" = {
      "x86_64-linux" = "sha256-Ynh0LZ9qYmVh+bwy6VSlMlI4/tYrdayNLtEJ7m2cK6E=";
      "aarch64-linux" = "sha256-XsCDuNNJJMkT43rBTSqlv5i7voPKEC58K/KNv7YbcAo=";
      "x86_64-darwin" = "sha256-8yWiAbVO9ljkhIJo+9xIIcwk0PH2ElhHVTNcmRuTTKw=";
      "aarch64-darwin" = "sha256-beYTI4hCu9k0STLwJnqHBX4lrqir4S2Nf+X1UItWPrA=";
    };
    "5.0.0-nightly.20260324" = {
      "x86_64-linux" = "sha256-eHWnqCwjKIRhva8JvfBTobC7sAZrHis7x/uMoHUY4XQ=";
      "aarch64-linux" = "sha256-91DwZa7qJ7XbIEVUljFxhhYPzNUJY1fFPTgmBocwHj0=";
      "x86_64-darwin" = "sha256-viH5nBgEmcB/7192Xv9jY54OavJ4qcxtPaxPJq9ajKs=";
      "aarch64-darwin" = "sha256-x1vc00QiQCASBOOaOe8zV5bZKp4NVTfgpfEoexHgHZ8=";
    };
  };
}
