{ pkgs ? import <nixpkgs> { }
, lib ? pkgs.lib
, version ? "1.0.0-beta.13"
}:

let
  # Map Nix system to Noir's platform naming
  platformInfo = {
    "x86_64-linux" = {
      target = "x86_64-unknown-linux-gnu";
    };
    "aarch64-linux" = {
      target = "aarch64-unknown-linux-gnu";
    };
    "x86_64-darwin" = {
      target = "x86_64-apple-darwin";
    };
    "aarch64-darwin" = {
      target = "aarch64-apple-darwin";
    };
  };

  # Import hashes from external file (generated by update-hashes.sh)
  hashes = (import ./hashes.nix).noir;

  info = platformInfo.${pkgs.stdenv.hostPlatform.system} or (throw "Unsupported platform: ${pkgs.stdenv.hostPlatform.system}");

  # Construct the download URL
  url = "https://github.com/noir-lang/noir/releases/download/v${version}/nargo-${info.target}.tar.gz";

  # Get hash for this version/platform, or use fakeHash for new versions
  hash = hashes.${version}.${pkgs.stdenv.hostPlatform.system} or lib.fakeHash;

in
pkgs.stdenv.mkDerivation {
  pname = "noir";
  inherit version;

  src = pkgs.fetchurl {
    inherit url hash;
  };

  nativeBuildInputs = [ pkgs.makeWrapper ];

  sourceRoot = ".";

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin

    # Copy the nargo binary
    cp nargo $out/bin/nargo
    chmod +x $out/bin/nargo

    runHook postInstall
  '';

  meta = with lib; {
    description = "Noir language tools (nargo) - ${version}";
    homepage = "https://noir-lang.org";
    license = licenses.mit;
    platforms = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
    mainProgram = "nargo";
  };
}
